export const TIER_STYLES = {
  unranked: { color: "#8a8a9a" },
  bronze: { color: "#b06b3a" },
  argent: { color: "#b8bec7" },
  or: { color: "#e0b23e" },
  platine: { color: "#5fd0c9" },
  emeraude: { color: "#3fbf6c" },
  rubis: { color: "#e0435f" },
  saphir: { color: "#3f7fe0" },
  diamant: { color: "#8ae0ff" },
  maitre: { color: "#c15fe0" },
  grand_maitre: { color: "#ffcf40" },
  top500: { color: "#ffcf40" },
  top100: { color: "#ffc11a" },
  top50: { color: "#ffaf00" },
  top10: { color: "#ff9200" },
  rank_one: { color: "#ff6a00" },
};
